<a href="https://colab.research.google.com/github/saktheeswaranswan/random-math-addition-data-for-rnn-generator/blob/main/Automl_hyper_parameter_tune_in_machine_learning_all_ml_codes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Load the iris dataset
data = pd.read_csv('/content/Iris.csv')

# Split the data into features and target variable
X = data.drop('Species', axis=1)
y = data['Species']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Train the classifier
clf = RandomForestClassifier(n_estimators=100, random_state=0)
clf.fit(X_train, y_train)

# Make predictions on the test set
y_pred = clf.predict(X_test)

# Evaluate the classifier's accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)


Accuracy:  1.0


In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import RandomizedSearchCV
import numpy as np

# Load the iris dataset
data = pd.read_csv('/content/Iris.csv')

# Split the data into features and target variable
X = data.drop('Species', axis=1)
y = data['Species']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Define the random search hyperparameters
param_distributions = {
    'n_estimators': np.arange(10, 200, 10),
    'max_depth': np.arange(1, 20),
    'min_samples_split': np.arange(2, 10),
    'min_samples_leaf': np.arange(1, 10)
}

# Perform random search
rnd_search = RandomizedSearchCV(RandomForestClassifier(), param_distributions, n_iter=100, cv=5)
rnd_search.fit(X_train, y_train)

# Get the best hyperparameters
print("Best parameters: ", rnd_search.best_params_)

# Train the classifier with the best hyperparameters
clf = RandomForestClassifier(**rnd_search.best_params_)
clf.fit(X_train, y_train)

# Make predictions on the test set
y_pred = clf.predict(X_test)

# Evaluate the classifier's accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)


Best parameters:  {'n_estimators': 30, 'min_samples_split': 6, 'min_samples_leaf': 7, 'max_depth': 4}
Accuracy:  1.0


In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import numpy as np

# Load the iris dataset
data = pd.read_csv('/content/Iris.csv')

# Split the data into features and target variable
X = data.drop('Species', axis=1)
y = data['Species']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Define the random search hyperparameters
param_distributions = {
    'n_estimators': np.arange(10, 200, 10),
    'max_depth': np.arange(1, 20),
    'min_samples_split': np.arange(2, 10),
    'min_samples_leaf': np.arange(1, 10)
}

# Perform random search
rnd_search = RandomizedSearchCV(RandomForestClassifier(), param_distributions, n_iter=100, cv=5)
rnd_search.fit(X_train, y_train)

# Get the best hyperparameters
print("Best parameters: ", rnd_search.best_params_)

# Train the classifier with the best hyperparameters
clf = RandomForestClassifier(**rnd_search.best_params_)
clf.fit(X_train, y_train)

# Make predictions on the test set
y_pred = clf.predict(X_test)

# Evaluate the classifier's accuracy
precision, recall, f1_score, support = precision_recall_fscore_support(y_test, y_pred, average='macro')

print("Precision: ", precision)
print("Recall: ", recall)
print("F1 score: ", f1_score)


Best parameters:  {'n_estimators': 160, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_depth': 18}
Precision:  1.0
Recall:  1.0
F1 score:  1.0


In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support

# Load the iris dataset from a csv file
data = pd.read_csv("/content/Iris.csv")
X = data.drop("Species", axis=1)
y = data["Species"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Define the parameter grid for grid search
param_grid = {'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 'kernel': ['linear', 'rbf']}

# Perform grid search to find the best parameters
grid_search = GridSearchCV(SVC(), param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Use the best parameters to train the SVM model
svm = SVC(C=grid_search.best_params_['C'], gamma=grid_search.best_params_['gamma'], kernel=grid_search.best_params_['kernel'])
svm.fit(X_train, y_train)

# Predict the target values for the test set
y_pred = svm.predict(X_test)

# Evaluate the model performance
conf_matrix = confusion_matrix(y_test, y_pred)
precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred, average='macro')
print("Confusion Matrix:")
print(conf_matrix)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1_score)


Confusion Matrix:
[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
Precision: 1.0
Recall: 1.0
F1 Score: 1.0


In [8]:
!pip install tpot


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.2/87.2 KB 8.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 MB 7.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.9/139.9 KB 20.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for stopit: filename=stopit-1.1.2-py3-none-any.whl size=11953 sha256=823d6eadc035f75cf23b2014dd52f62fc2f9fb7324edb31e51f038d516a977c5
  Stored in directory: /root/.cache/pip/wheels/a8/bb/8f/6b9328d23c2dcedbfeb8498b9f650d55d463089e3b8fc0bfb2
Successfully built stopit
  Attempting uninstall: xgboost
    Found existing installation: xgboost 0.90
    Uninstalling xgboost-0.90:
      Successfully uninstalled xgboost-0.90


In [9]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tpot import TPOTClassifier
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support

# Load the iris dataset from a csv file
data = pd.read_csv("/content/Iris.csv")
X = data.drop("Species", axis=1)
y = data["Species"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Train the autoML classifier using TPOT
tpot = TPOTClassifier(generations=5, population_size=50, verbosity=2, n_jobs=-1)
tpot.fit(X_train, y_train)

# Use the best parameters to train the SVM model
svm = tpot.fitted_pipeline_

# Predict the target values for the test set
y_pred = svm.predict(X_test)

# Evaluate the model performance
conf_matrix = confusion_matrix(y_test, y_pred)
precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred, average='macro')
print("Confusion Matrix:")
print(conf_matrix)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1_score)


Optimization Progress:   0%|          | 0/300 [00:00<?, ?pipeline/s]


Generation 1 - Current best internal CV score: 1.0

Generation 2 - Current best internal CV score: 1.0

Generation 3 - Current best internal CV score: 1.0

Generation 4 - Current best internal CV score: 1.0

Generation 5 - Current best internal CV score: 1.0

Best pipeline: RandomForestClassifier(input_matrix, bootstrap=True, criterion=gini, max_features=0.55, min_samples_leaf=13, min_samples_split=17, n_estimators=100)
Confusion Matrix:
[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
Precision: 1.0
Recall: 1.0
F1 Score: 1.0


In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tpot import TPOTClassifier
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support
from sklearn.ensemble import AdaBoostClassifier

# Load the iris dataset from a csv file
data = pd.read_csv("/content/Iris.csv")
X = data.drop("Species", axis=1)
y = data["Species"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Train the autoML classifier using TPOT
tpot = TPOTClassifier(generations=5, population_size=50, verbosity=2, n_jobs=-1, scoring='f1_macro', config_dict='TPOT light')
tpot.fit(X_train, y_train)

# Use the best parameters to train the Adaboost classifier
adaboost = tpot.fitted_pipeline_

# Predict the target values for the test set
y_pred = adaboost.predict(X_test)

# Evaluate the model performance
conf_matrix = confusion_matrix(y_test, y_pred)
precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred, average='macro')
print("Confusion Matrix:")
print(conf_matrix)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1_score)


Optimization Progress:   0%|          | 0/300 [00:00<?, ?pipeline/s]


Generation 1 - Current best internal CV score: 1.0

Generation 2 - Current best internal CV score: 1.0

Generation 3 - Current best internal CV score: 1.0

Generation 4 - Current best internal CV score: 1.0

Generation 5 - Current best internal CV score: 1.0

Best pipeline: DecisionTreeClassifier(input_matrix, criterion=gini, max_depth=5, min_samples_leaf=19, min_samples_split=16)
Confusion Matrix:
[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]
Precision: 0.9761904761904763
Recall: 0.9444444444444445
F1 Score: 0.957351290684624


In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tpot import TPOTClassifier
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support
from sklearn.ensemble import RandomForestClassifier

# Load the iris dataset from a csv file
data = pd.read_csv("/content/Iris.csv")
X = data.drop("Species", axis=1)
y = data["Species"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Train the autoML classifier using TPOT
tpot = TPOTClassifier(generations=5, population_size=50, verbosity=2, n_jobs=-1, scoring='f1_macro', config_dict='TPOT light')
tpot.fit(X_train, y_train)

# Use the best parameters to train the Random Forest classifier
random_forest = tpot.fitted_pipeline_

# Predict the target values for the test set
y_pred = random_forest.predict(X_test)

# Evaluate the model performance
conf_matrix = confusion_matrix(y_test, y_pred)
precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred, average='macro')
print("Confusion Matrix:")
print(conf_matrix)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1_score)


Optimization Progress:   0%|          | 0/300 [00:00<?, ?pipeline/s]


Generation 1 - Current best internal CV score: 1.0

Generation 2 - Current best internal CV score: 1.0

Generation 3 - Current best internal CV score: 1.0

Generation 4 - Current best internal CV score: 1.0

Generation 5 - Current best internal CV score: 1.0

Best pipeline: KNeighborsClassifier(input_matrix, n_neighbors=89, p=2, weights=distance)
Confusion Matrix:
[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
Precision: 1.0
Recall: 1.0
F1 Score: 1.0


In [13]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tpot import TPOTClassifier
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support
from sklearn.neural_network import MLPClassifier

# Load the iris dataset from a csv file
data = pd.read_csv("/content/Iris.csv")
X = data.drop("Species", axis=1)
y = data["Species"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Train the autoML classifier using TPOT
tpot = TPOTClassifier(generations=5, population_size=50, verbosity=2, n_jobs=-1, scoring='f1_macro', config_dict='TPOT light')
tpot.fit(X_train, y_train)

# Use the best parameters to train the Neural Network classifier
neural_network = tpot.fitted_pipeline_

# Predict the target values for the test set
y_pred = neural_network.predict(X_test)

# Evaluate the model performance
conf_matrix = confusion_matrix(y_test, y_pred)
precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred, average='macro')
print("Confusion Matrix:")
print(conf_matrix)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1_score)


Optimization Progress:   0%|          | 0/300 [00:00<?, ?pipeline/s]


Generation 1 - Current best internal CV score: 1.0

Generation 2 - Current best internal CV score: 1.0

Generation 3 - Current best internal CV score: 1.0

Generation 4 - Current best internal CV score: 1.0

Generation 5 - Current best internal CV score: 1.0

Best pipeline: DecisionTreeClassifier(input_matrix, criterion=gini, max_depth=2, min_samples_leaf=13, min_samples_split=3)
Confusion Matrix:
[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]
Precision: 0.9761904761904763
Recall: 0.9444444444444445
F1 Score: 0.957351290684624


In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

# Load the Iris dataset
iris = datasets.load_iris()

# Create a DataFrame from the Iris data
df = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])

# Assign the target variable as "Species"
df['Species'] = df['target'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})

# Split the data into training and testing sets
X = df.iloc[:, :-2].values
y = df.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Fit KNN and Decision Trees models to the data
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

# Predict using KNN and Decision Trees models
y_pred_knn = knn.predict(X_test)
y_pred_dt = dt.predict(X_test)

# Evaluate the models using accuracy score
acc_knn = accuracy_score(y_test, y_pred_knn)
acc_dt = accuracy_score(y_test, y_pred_dt)

# Plot confusion matrix for KNN and Decision Trees models
cm_knn = confusion_matrix(y_test, y_pred_knn)
cm_dt = confusion_matrix(y_test, y_pred_dt)

# Print accuracy score and confusion matrix for KNN and Decision Trees models
print("KNN Accuracy:", acc_knn)
print("KNN Confusion Matrix:", cm_knn)
print("Decision Trees Accuracy:", acc_dt)
print("Decision Trees Confusion Matrix:", cm_dt)


KNN Accuracy: 0.9333333333333333
KNN Confusion Matrix: [[ 9  0  0]
 [ 0 10  0]
 [ 0  2  9]]
Decision Trees Accuracy: 0.9666666666666667
Decision Trees Confusion Matrix: [[ 9  0  0]
 [ 0 10  0]
 [ 0  1 10]]


In [16]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
import matplotlib.pyplot as plt
import seaborn as sns

# Load the Iris dataset
df = pd.read_csv("/content/Iris.csv")

# Define the target variable
y = df['Species']

# Drop the target variable and unnecessary columns
df.drop(['Id', 'Species'], axis=1, inplace=True)

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2, random_state=42)

# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# KNN Classifier
knn = KNeighborsClassifier()

# Define the parameter grid for KNN
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11, 13],
    'weights': ['uniform', 'distance'],
    'p': [1, 2]
}

# Grid Search
grid_search = GridSearchCV(knn, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Print the best parameters and best score
print("Best Parameters for KNN: ", grid_search.best_params_)
print("Best Score for KNN: ", grid_search.best_score_)

# Random Search
random_search = RandomizedSearchCV(knn, param_distributions=param_grid, cv=5, scoring='accuracy', n_iter=20)
random_search.fit(X_train, y_train)

# Print the best parameters and best score
print("Best Parameters for KNN (Random Search): ", random_search.best_params_)
print("Best Score for KNN (Random Search): ", random_search.best_score_)

# Decision Tree Classifier
dt = DecisionTreeClassifier()

# Define the parameter grid for Decision Tree
param_grid = {
    'max_depth': [3, 5, 7, 9, 11, 13],
    'min_samples_split': [2, 4, 6, 8, 10],
    'min_samples_leaf': [1, 2, 4, 6, 8]
}

# Grid Search
grid_search = GridSearchCV(dt, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)


# Print the best parameters and best score
print("Best Parameters for decision tree: ", grid_search.best_params_)
print("Best Score for decision tree: ", grid_search.best_score_)


Best Parameters for KNN:  {'n_neighbors': 7, 'p': 1, 'weights': 'distance'}
Best Score for KNN:  0.9583333333333334
Best Parameters for KNN (Random Search):  {'weights': 'uniform', 'p': 1, 'n_neighbors': 9}
Best Score for KNN (Random Search):  0.9583333333333334
Best Parameters for decision tree:  {'max_depth': 3, 'min_samples_leaf': 4, 'min_samples_split': 2}
Best Score for decision tree:  0.95


In [15]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# Load the iris dataset
iris_df = pd.read_csv("/content/Iris.csv")

# Encode the target variable
le = LabelEncoder()
iris_df['Species'] = le.fit_transform(iris_df['Species'])

# Split the dataset into train and test sets
X = iris_df.drop("Species", axis=1)
y = iris_df["Species"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Grid Search for Decision Tree Classifier
param_grid = {'max_depth': [1, 5, 10, 20, 50],
              'min_samples_split': [2, 5, 10, 20],
              'min_samples_leaf': [1, 5, 10, 20]}

dt = DecisionTreeClassifier()
grid_search = GridSearchCV(dt, param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Print the best parameters and best score
print("Best Parameters for Decision Tree (Grid Search): ", grid_search.best_params_)
print("Best Score for Decision Tree (Grid Search): ", grid_search.best_score_)

# Random Search for Decision Tree Classifier
param_grid = {'max_depth': [1, 5, 10, 20, 50],
              'min_samples_split': [2, 5, 10, 20],
              'min_samples_leaf': [1, 5, 10, 20]}

dt = DecisionTreeClassifier()
random_search = RandomizedSearchCV(dt, param_distributions=param_grid, n_iter=100, cv=5)
random_search.fit(X_train, y_train)

# Print the best parameters and best score
print("Best Parameters for Decision Tree (Random Search): ", random_search.best_params_)
print("Best Score for Decision Tree (Random Search): ", random_search.best_score_)


Best Parameters for Decision Tree (Grid Search):  {'max_depth': 5, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best Score for Decision Tree (Grid Search):  0.9916666666666668


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_search.py:292: UserWarning: The total space of parameters 80 is smaller than n_iter=100. Running 80 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


Best Parameters for Decision Tree (Random Search):  {'min_samples_split': 2, 'min_samples_leaf': 1, 'max_depth': 5}
Best Score for Decision Tree (Random Search):  0.9916666666666668


In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import precision_recall_fscore_support, accuracy_score
from sklearn.model_selection import RandomizedSearchCV
import numpy as np

# Load Iris data
data = pd.read_csv('/content/Iris.csv')

# Split into features and target
X = data.drop(['Species'], axis=1)
y = data['Species']

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Define a base MLP Classifier
mlp = MLPClassifier(max_iter=1000)

# Define a hyperparameter grid to search over
param_grid = {
    'hidden_layer_sizes': [(10,), (50,), (100,)],
    'activation': ['relu', 'tanh', 'logistic'],
    'solver': ['adam', 'lbfgs'],
    'alpha': [0.0001, 0.001, 0.01],
}

# Use RandomizedSearchCV to tune hyperparameters
random_search = RandomizedSearchCV(mlp, param_grid, cv=5, scoring='accuracy', n_iter=20)
random_search.fit(X_train, y_train)

# Print the best parameters and best score
print("Best Parameters for MLP Classifier (Random Search): ", random_search.best_params_)
print("Best Score for MLP Classifier (Random Search): ", random_search.best_score_)

# Predict on test set using best parameters
y_pred = random_search.predict(X_test)

# Calculate precision, recall, f1-score, and accuracy
precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred, average='weighted')
accuracy = accuracy_score(y_test, y_pred)

# Print metrics
print("Precision: ", precision)
print("Recall: ", recall)
print("f1-score: ", f1_score)
print("Accuracy: ", accuracy)


/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron

Best Parameters for MLP Classifier (Random Search):  {'solver': 'adam', 'hidden_layer_sizes': (100,), 'alpha': 0.0001, 'activation': 'logistic'}
Best Score for MLP Classifier (Random Search):  1.0
Precision:  1.0
Recall:  1.0
f1-score:  1.0
Accuracy:  1.0


In [20]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# Load iris dataset
df = pd.read_csv("/content/Iris.csv")

# Define target variable
y = df['Species']

# Drop target variable and set input variables
X = df.drop(['Species'], axis=1)

# Initialize MLPClassifier
mlp = MLPClassifier(max_iter=1000)

# Define hyperparameters to tune
param_grid = {'hidden_layer_sizes': [(10,), (50,), (100,)],
              'alpha': [0.0001, 0.001, 0.01]}

# Perform grid search
grid_search = GridSearchCV(mlp, param_grid, cv=3, scoring='accuracy', return_train_score=True)
grid_search.fit(X, y)

# Print best parameters and best score
print("Best Parameters for MLP (Grid Search): ", grid_search.best_params_)
print("Best Score for MLP (Grid Search): ", grid_search.best_score_)

# Predict using best parameters
mlp = MLPClassifier(max_iter=1000, **grid_search.best_params_)
mlp.fit(X, y)
y_pred = mlp.predict(X)

# Print evaluation metrics
print("Accuracy:", accuracy_score(y, y_pred))
print("Classification Report:")
print(classification_report(y, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y, y_pred))


/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Best Parameters for MLP (Grid Search):  {'alpha': 0.001, 'hidden_layer_sizes': (10,)}
Best Score for MLP (Grid Search):  0.8133333333333334
Accuracy: 0.9066666666666666
Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        50
Iris-versicolor       0.88      0.84      0.86        50
 Iris-virginica       0.85      0.88      0.86        50

       accuracy                           0.91       150
      macro avg       0.91      0.91      0.91       150
   weighted avg       0.91      0.91      0.91       150

Confusion Matrix:
[[50  0  0]
 [ 0 42  8]
 [ 0  6 44]]


/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [21]:
# Importing libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Load data
df = pd.read_csv("/content/Iris.csv")
X = df.iloc[:, :-1]
y = df["Species"]

# Split data into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Create an SVM classifier
svm_clf = svm.SVC()

# Define hyperparameters and possible values for grid search
grid_params = {'C': [0.1, 1, 10, 100], 'kernel': ['linear', 'rbf']}

# Use grid search to tune the hyperparameters
grid_search = GridSearchCV(svm_clf, grid_params, scoring='accuracy', cv=5)
grid_search.fit(X_train, y_train)

# Use randomized search to tune the hyperparameters
random_search = RandomizedSearchCV(svm_clf, grid_params, n_iter=50, scoring='accuracy', cv=5, random_state=0)
random_search.fit(X_train, y_train)

# Make predictions using the best hyperparameters
y_pred_grid = grid_search.predict(X_test)
y_pred_random = random_search.predict(X_test)

# Evaluate the performance using accuracy, precision, recall, and f1 score
grid_acc = accuracy_score(y_test, y_pred_grid)
grid_precision = precision_score(y_test, y_pred_grid, average='weighted')
grid_recall = recall_score(y_test, y_pred_grid, average='weighted')
grid_f1 = f1_score(y_test, y_pred_grid, average='weighted')

random_acc = accuracy_score(y_test, y_pred_random)
random_precision = precision_score(y_test, y_pred_random, average='weighted')
random_recall = recall_score(y_test, y_pred_random, average='weighted')
random_f1 = f1_score(y_test, y_pred_random, average='weighted')

# Print the results
print("Grid Search Results:")
print("Accuracy: ", grid_acc)
print("Precision: ", grid_precision)
print("Recall: ", grid_recall)
print("F1 Score: ", grid_f1)

print("Random Search Results:")
print("Accuracy: ", random_acc)
print("Precision: ", random_precision)
print("Recall: ", random_recall)
print("F1 Score: ", random_f1)


Grid Search Results:
Accuracy:  1.0
Precision:  1.0
Recall:  1.0
F1 Score:  1.0
Random Search Results:
Accuracy:  1.0
Precision:  1.0
Recall:  1.0
F1 Score:  1.0


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_search.py:292: UserWarning: The total space of parameters 8 is smaller than n_iter=50. Running 8 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


In [22]:
# Importing libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Load data
df = pd.read_csv("/content/Iris.csv")
X = df.iloc[:, :-1]
y = df["Species"]

# Split data into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Create an SVM classifier
svm_clf = svm.SVC()

# Define hyperparameters and possible values for grid search
grid_params = {'C': [0.1, 1, 10, 100], 'kernel': ['linear', 'rbf']}

# Use grid search to tune the hyperparameters
grid_search = GridSearchCV(svm_clf, grid_params, scoring='accuracy', cv=5)
grid_search.fit(X_train, y_train)

# Use randomized search to tune the hyperparameters
random_search = RandomizedSearchCV(svm_clf, grid_params, n_iter=50, scoring='accuracy', cv=5, random_state=0)
random_search.fit(X_train, y_train)

# Make predictions using the best hyperparameters
y_pred_grid = grid_search.predict(X_test)
y_pred_random = random_search.predict(X_test)

# Evaluate the performance using accuracy, precision, recall, and f1 score
grid_acc = accuracy_score(y_test, y_pred_grid)
grid_precision = precision_score(y_test, y_pred_grid, average='weighted')
grid_recall = recall_score(y_test, y_pred_grid, average='weighted')
grid_f1 = f1_score(y_test, y_pred_grid, average='weighted')

random_acc = accuracy_score(y_test, y_pred_random)
random_precision = precision_score(y_test, y_pred_random, average='weighted')
random_recall = recall_score(y_test, y_pred_random, average='weighted')
random_f1 = f1_score(y_test, y_pred_random, average='weighted')

# Print the results
print("Grid Search Results:")
print("Accuracy: ", grid_acc)
print("Precision: ", grid_precision)
print("Recall: ", grid_recall)
print("F1 Score: ", grid_f1)

print("Random Search Results:")
print("Accuracy: ", random_acc)
print("Precision: ", random_precision)
print("Recall: ", random_recall)
print("F1 Score: ", random_f1)


Grid Search Results:
Accuracy:  1.0
Precision:  1.0
Recall:  1.0
F1 Score:  1.0
Random Search Results:
Accuracy:  1.0
Precision:  1.0
Recall:  1.0
F1 Score:  1.0


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_search.py:292: UserWarning: The total space of parameters 8 is smaller than n_iter=50. Running 8 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
